apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
      version: green
  template:
    metadata:
      labels:
        app: messaging
        version: green
    spec:
      containers:
        - name: messaging
          image: messaging_app:1.1
          ports:
            - containerPort: 8000
